export const CHANGE_FILTER_OPTION = 'CHANGE_FILTER_OPTION';
export const SEARCH_ITEM = 'SEARCH_ITEM';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SET = 'SET';
export const RESET_DEVICE_BUILDER_FORM = 'RESET_DEVICE_BUILDER_FORM';
export const ADD_DEVICE = 'ADD_DEVICE';
export const LOAD_DEVICES = 'LOAD_DEVICES';
export const DELETE_DEVICE = 'DELETE_DEVICE';
<<<<<<< HEAD
export const UPDATE_CURRENT_USERS = 'UPDATE_CURRENT_USERS';
export const UPDATE_CURRENT_REQUEST ='UPDATE_CURRENT_REQUEST';
=======
export const LOAD_DEVICES_ASYNC = 'LOAD_DEVICES_ASYNC';
export const LOAD_DEVICE_ASYNC = 'LOAD_DEVICE_ASYNC';
export const DELETE_DEVICE_ASYNC = 'DELETE_DEVICE_ASYNC';
export const ADD_DEVICE_ASYNC = 'ADD_DEVICE_ASYNC';
>>>>>>> 9e9469c7b79ae27e46122ece7cee0813c4b29943
